[project]
name = "aircraft-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Виталий Якимов",email = "fess.888@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "config (>=0.5.1,<0.6.0)",
    "psycopg[binary] (>=3.3.6,<4.0.0)",
    "dotenv (>=0.9.9,<0.10.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
